name: Scrape series
on:
  workflow_dispatch:
    inputs:
      episode-start:
        description: "Starting Episode"
        required: true
        type: number
        default: 1
      episode-end:
        description: "Ending Episode"
        required: true
        type: number
        default: 12
      series-id:
        description: "Series Id"
        type: string
        required: true
jobs:
  init-tasks:
    name: Initialize tasks from inputs
    runs-on: ubuntu-latest
    outputs:
      episode-numbers: ${{ steps.generate-episode.outputs.output }}
    if: ${{ inputs.episode-start <= inputs.episode-end }}
    steps:
      - name: Generate array of episode numbers
        id: generate-episode
        run: echo "output=[$(seq -s, ${{ inputs.episode-start }} ${{ inputs.episode-end }})]" >> "$GITHUB_OUTPUT"
  scrape-task:
    name: Scrape task
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - init-tasks
    strategy:
      matrix:
        episode-number: ${{ fromJSON(needs.init-tasks.outputs.episode-numbers) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: npm run build
      - run: npm run run-task -- "${{ inputs.series-id }}" "${{ matrix.episode-number }}"
      - uses: actions/upload-artifact@v4
        id: upload-error-image
        with:
          name: ${{ matrix.episode-number }}-error.webp
          path: error.webp
          if-no-files-found: ignore
      - if: ${{ steps.upload-error-image.outputs.artifact-url != '' }}
        run: sed -i -e 's/null/"${{steps.upload-error-image.outputs.artifact-url}}"/g' output.json
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.episode-number }}.json
          path: output.json
          if-no-files-found: error
  summarize-result:
    name: Summarize results
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - init-tasks
      - scrape-task
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: npm run build
      - uses: actions/download-artifact@v4
        with:
          path: output
          pattern: "*.json"
      - run: ls -la ./output
